<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>James Routley | Feed</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="../styles.css"
      media="screen"
    />
  </head>
  <body>
    <a href="/index.html">Back</a>
    <a href="https://www.sheshbabu.com/posts/rust-error-handling/">Original</a>
    <h1>Beginner&#39;s Guide to Error Handling in Rust</h1>
    
    <div id="readability-page-1" class="page"><div><p>Error handling in Rust is very different if you’re coming from other languages. In languages like Java, JS, Python etc, you usually <code>throw</code> exceptions and <code>return</code> successful values. In Rust, you return something called a <code>Result</code>.</p>
<p>The <code>Result&lt;T, E&gt;</code> type is an <a href="https://doc.rust-lang.org/book/ch06-01-defining-an-enum.html" target="_blank" rel="noopener">enum</a> that has two variants - <code>Ok(T)</code> for successful value or <code>Err(E)</code> for error value:</p>
<pre><code><span>enum</span> Result<span>&lt;</span>T<span>,</span> E<span>&gt;</span> <span>{</span>
   <span>Ok</span><span>(</span>T<span>)</span><span>,</span>
   <span>Err</span><span>(</span>E<span>)</span><span>,</span>
<span>}</span></code></pre>
<p>Returning errors instead of throwing them is a paradigm shift in error handling. If you’re new to Rust, there will be some friction initially as it requires you to reason about errors in a different way.</p>
<p>In this post, I’ll go through some common error handling patterns so you gradually become familiar with how things are done in Rust:</p>
<ul>
<li>Ignore the error</li>
<li>Terminate the program</li>
<li>Use a fallback value</li>
<li>Bubble up the error</li>
<li>Bubble up multiple errors</li>
<li>Match boxed errors</li>
<li>Libraries vs Applications</li>
<li>Create custom errors</li>
<li>Bubble up custom errors</li>
<li>Match custom errors</li>
</ul>
<h2 id="Ignore-the-error"><a href="#Ignore-the-error" title="Ignore the error"></a>Ignore the error</h2><p>Let’s start with the simplest scenario where we just ignore the error. This sounds careless but has a couple of legitimate use cases:</p>
<ul>
<li>We’re prototyping our code and don’t want to spend time on error handling.</li>
<li>We’re confident that the error won’t occur.</li>
</ul>
<p>Let’s say that we’re reading a file which we’re pretty sure would be present:</p>
<pre><code><span>use</span> std<span>:</span><span>:</span>fs<span>;</span>

<span>fn</span> <span>main</span><span>(</span><span>)</span> <span>{</span>
  <span>let</span> content <span>=</span> fs<span>:</span><span>:</span><span>read_to_string</span><span>(</span><span>&#34;./Cargo.toml&#34;</span><span>)</span><span>.</span><span>unwrap</span><span>(</span><span>)</span><span>;</span>
  <span>println!</span><span>(</span><span>&#34;{}&#34;</span><span>,</span> content<span>)</span>
<span>}</span></code></pre>
<p>Even though we know that the file would be present, the compiler has no way of knowing that. So we use <code>unwrap</code> to tell the compiler to trust us and return the value inside. If the <code>read_to_string</code> function returns an <code>Ok()</code> value, <code>unwrap</code> will get the contents of <code>Ok</code> and assign it to the <code>content</code> variable. If it returns an error, it will “panic”. Panic either terminates the program or exits the current thread.</p>
<p>Note that <code>unwrap</code> is used in quite a lot of Rust examples to skip error handling. This is mostly done for convenience and shouldn’t be used in real code as it is.</p>
<h2 id="Terminate-the-program"><a href="#Terminate-the-program" title="Terminate the program"></a>Terminate the program</h2><p>Some errors cannot be handled or recovered from. In these cases, it’s better to <em>fail fast</em> by terminating the program.</p>
<p>Let’s use the same example as above - we’re reading a file which we’re sure to be present. Let’s imagine that, for this program, that file is absolutely important without which it won’t work properly. If for some reason, this file is absent, it’s better to terminate the program.</p>
<p>We can use <code>unwrap</code> as before or use <code>expect</code> - it’s same as <code>unwrap</code> but lets us add extra error message.</p>
<pre><code><span>use</span> std<span>:</span><span>:</span>fs<span>;</span>

<span>fn</span> <span>main</span><span>(</span><span>)</span> <span>{</span>
  <span>let</span> content <span>=</span> fs<span>:</span><span>:</span><span>read_to_string</span><span>(</span><span>&#34;./Cargo.toml&#34;</span><span>)</span><span>.</span><span>expect</span><span>(</span><span>&#34;Can&#39;t read Cargo.toml&#34;</span><span>)</span><span>;</span>
  <span>println!</span><span>(</span><span>&#34;{}&#34;</span><span>,</span> content<span>)</span>
<span>}</span></code></pre>
<p>See also: <a href="https://doc.rust-lang.org/std/macro.panic.html" target="_blank" rel="noopener"><code>panic!</code></a></p>
<h2 id="Use-a-fallback-value"><a href="#Use-a-fallback-value" title="Use a fallback value"></a>Use a fallback value</h2><p>In some cases, you can handle the error by falling back to a default value.</p>
<p>For example, let’s say we’re writing a server and the port it listens to can be configured using an environment variable. If the environment variable is not set, accessing that value would result in an error. But we can easily handle that by falling back to a default value.</p>
<pre><code><span>use</span> std<span>:</span><span>:</span>env<span>;</span>

<span>fn</span> <span>main</span><span>(</span><span>)</span> <span>{</span>
  <span>let</span> port <span>=</span> env<span>:</span><span>:</span><span>var</span><span>(</span><span>&#34;PORT&#34;</span><span>)</span><span>.</span><span>unwrap_or</span><span>(</span><span>&#34;3000&#34;</span><span>.</span><span>to_string</span><span>(</span><span>)</span><span>)</span><span>;</span>
  <span>println!</span><span>(</span><span>&#34;{}&#34;</span><span>,</span> port<span>)</span><span>;</span>
<span>}</span></code></pre>
<p>Here, we’ve used a variation of <code>unwrap</code> called <code>unwrap_or</code> which lets us supply default values.</p>
<p>See also: <a href="https://doc.rust-lang.org/std/result/enum.Result.html#method.unwrap_or_else" target="_blank" rel="noopener"><code>unwrap_or_else</code></a>, <a href="https://doc.rust-lang.org/std/result/enum.Result.html#method.unwrap_or_default" target="_blank" rel="noopener"><code>unwrap_or_default</code></a></p>
<h2 id="Bubble-up-the-error"><a href="#Bubble-up-the-error" title="Bubble up the error"></a>Bubble up the error</h2><p>When you don’t have enough context to handle the error, you can bubble up (propagate) the error to the caller function.</p>
<p>Here’s a contrived example which uses a webservice to get the current year:</p>
<pre><code><span>use</span> std<span>:</span><span>:</span>collections<span>:</span><span>:</span>HashMap<span>;</span>

<span>fn</span> <span>main</span><span>(</span><span>)</span> <span>{</span>
  <span>match</span> <span>get_current_date</span><span>(</span><span>)</span> <span>{</span>
    <span>Ok</span><span>(</span>date<span>)</span> <span>=</span><span>&gt;</span> <span>println!</span><span>(</span><span>&#34;We&#39;ve time travelled to {}!!&#34;</span><span>,</span> date<span>)</span><span>,</span>
    <span>Err</span><span>(</span>e<span>)</span> <span>=</span><span>&gt;</span> <span>eprintln!</span><span>(</span><span>&#34;Oh noes, we don&#39;t know which era we&#39;re in! :( \n  {}&#34;</span><span>,</span> e<span>)</span><span>,</span>
  <span>}</span>
<span>}</span>

<span>fn</span> <span>get_current_date</span><span>(</span><span>)</span> <span>-&gt;</span> Result<span>&lt;</span>String<span>,</span> reqwest<span>:</span><span>:</span>Error<span>&gt;</span> <span>{</span>
  <span>let</span> url <span>=</span> <span>&#34;https://postman-echo.com/time/object&#34;</span><span>;</span>
  <span>let</span> result <span>=</span> reqwest<span>:</span><span>:</span>blocking<span>:</span><span>:</span><span>get</span><span>(</span>url<span>)</span><span>;</span>

  <span>let</span> response <span>=</span> <span>match</span> result <span>{</span>
    <span>Ok</span><span>(</span>res<span>)</span> <span>=</span><span>&gt;</span> res<span>,</span>
    <span>Err</span><span>(</span>err<span>)</span> <span>=</span><span>&gt;</span> <span>return</span> <span>Err</span><span>(</span>err<span>)</span><span>,</span>
  <span>}</span><span>;</span>

  <span>let</span> body <span>=</span> response<span>.</span>json<span>:</span><span>:</span><span>&lt;</span>HashMap<span>&lt;</span>String<span>,</span> i32<span>&gt;&gt;</span><span>(</span><span>)</span><span>;</span>

  <span>let</span> json <span>=</span> <span>match</span> body <span>{</span>
    <span>Ok</span><span>(</span>json<span>)</span> <span>=</span><span>&gt;</span> json<span>,</span>
    <span>Err</span><span>(</span>err<span>)</span> <span>=</span><span>&gt;</span> <span>return</span> <span>Err</span><span>(</span>err<span>)</span><span>,</span>
  <span>}</span><span>;</span>

  <span>let</span> date <span>=</span> json<span>[</span><span>&#34;years&#34;</span><span>]</span><span>.</span><span>to_string</span><span>(</span><span>)</span><span>;</span>

  <span>Ok</span><span>(</span>date<span>)</span>
<span>}</span></code></pre>
<p>There are two function calls inside the <code>get_current_date</code> function (<code>get</code> and <code>json</code>) that return <code>Result</code> values. Since <code>get_current_date</code> doesn’t have context of what to do when they return errors, it uses pattern matching to propagate the errors to <code>main</code>.</p>
<p>Using pattern matching to handle multiple or nested errors can make your code “noisy”. Instead, we can rewrite the above code using the <a href="https://doc.rust-lang.org/book/ch09-02-recoverable-errors-with-result.html#a-shortcut-for-propagating-errors-the--operator" target="_blank" rel="noopener"><code>?</code> operator</a>:</p>
<pre><code><span>use</span> std<span>:</span><span>:</span>collections<span>:</span><span>:</span>HashMap<span>;</span>

<span>fn</span> <span>main</span><span>(</span><span>)</span> <span>{</span>
  <span>match</span> <span>get_current_date</span><span>(</span><span>)</span> <span>{</span>
    <span>Ok</span><span>(</span>date<span>)</span> <span>=</span><span>&gt;</span> <span>println!</span><span>(</span><span>&#34;We&#39;ve time travelled to {}!!&#34;</span><span>,</span> date<span>)</span><span>,</span>
    <span>Err</span><span>(</span>e<span>)</span> <span>=</span><span>&gt;</span> <span>eprintln!</span><span>(</span><span>&#34;Oh noes, we don&#39;t know which era we&#39;re in! :( \n  {}&#34;</span><span>,</span> e<span>)</span><span>,</span>
  <span>}</span>
<span>}</span>

<span>fn</span> <span>get_current_date</span><span>(</span><span>)</span> <span>-&gt;</span> Result<span>&lt;</span>String<span>,</span> reqwest<span>:</span><span>:</span>Error<span>&gt;</span> <span>{</span>
  <span>let</span> url <span>=</span> <span>&#34;https://postman-echo.com/time/object&#34;</span><span>;</span>
  <span>let</span> res <span>=</span> reqwest<span>:</span><span>:</span>blocking<span>:</span><span>:</span><span>get</span><span>(</span>url<span>)</span>?<span>.</span>json<span>:</span><span>:</span><span>&lt;</span>HashMap<span>&lt;</span>String<span>,</span> i32<span>&gt;&gt;</span><span>(</span><span>)</span>?<span>;</span>
  <span>let</span> date <span>=</span> res<span>[</span><span>&#34;years&#34;</span><span>]</span><span>.</span><span>to_string</span><span>(</span><span>)</span><span>;</span>

  <span>Ok</span><span>(</span>date<span>)</span>
<span>}</span></code></pre>
<p>This looks much cleaner!</p>
<p>The <code>?</code> operator is similar to <code>unwrap</code> but instead of panicking, it propagates the error to the calling function. One thing to keep in mind is that we can use the <code>?</code> operator only for functions that return a <code>Result</code> or <code>Option</code> type.</p>
<h2 id="Bubble-up-multiple-errors"><a href="#Bubble-up-multiple-errors" title="Bubble up multiple errors"></a>Bubble up multiple errors</h2><p>In the previous example, the <code>get</code> and <code>json</code> functions return a <code>reqwest::Error</code> error which we’ve propagated using the <code>?</code> operator. But what if we’ve another function call that returned a different error value?</p>
<p>Let’s extend the previous example by returning a formatted date instead of the year:</p>
<pre><code><span>+ use chrono::NaiveDate;</span>
  use std::collections::HashMap;

  fn main() {
    match get_current_date() {
      Ok(date) =&gt; println!(&#34;We&#39;ve time travelled to {}!!&#34;, date),
      Err(e) =&gt; eprintln!(&#34;Oh noes, we don&#39;t know which era we&#39;re in! :( \n  {}&#34;, e),
    }
  }

  fn get_current_date() -&gt; Result&lt;String, reqwest::Error&gt; {
    let url = &#34;https://postman-echo.com/time/object&#34;;
    let res = reqwest::blocking::get(url)?.json::&lt;HashMap&lt;String, i32&gt;&gt;()?;
<span>-   let date = res[&#34;years&#34;].to_string();</span>
<span>+   let formatted_date = format!(&#34;{}-{}-{}&#34;, res[&#34;years&#34;], res[&#34;months&#34;] + 1, res[&#34;date&#34;]);</span>
<span>+   let parsed_date = NaiveDate::parse_from_str(formatted_date.as_str(), &#34;%Y-%m-%d&#34;)?;</span>
<span>+   let date = parsed_date.format(&#34;%Y %B %d&#34;).to_string();</span>

    Ok(date)
  }</code></pre>
<p>The above code won’t compile as <code>parse_from_str</code> returns a <code>chrono::format::ParseError</code> error and not <code>reqwest::Error</code>.</p>
<p>We can fix this by <code>Box</code>ing the errors:</p>
<pre><code>  use chrono::NaiveDate;
  use std::collections::HashMap;

  fn main() {
    match get_current_date() {
      Ok(date) =&gt; println!(&#34;We&#39;ve time travelled to {}!!&#34;, date),
      Err(e) =&gt; eprintln!(&#34;Oh noes, we don&#39;t know which era we&#39;re in! :( \n  {}&#34;, e),
    }
  }

<span>- fn get_current_date() -&gt; Result&lt;String, reqwest::Error&gt; {</span>
<span>+ fn get_current_date() -&gt; Result&lt;String, Box&lt;dyn std::error::Error&gt;&gt; {</span>
    let url = &#34;https://postman-echo.com/time/object&#34;;
    let res = reqwest::blocking::get(url)?.json::&lt;HashMap&lt;String, i32&gt;&gt;()?;

    let formatted_date = format!(&#34;{}-{}-{}&#34;, res[&#34;years&#34;], res[&#34;months&#34;] + 1, res[&#34;date&#34;]);
    let parsed_date = NaiveDate::parse_from_str(formatted_date.as_str(), &#34;%Y-%m-%d&#34;)?;
    let date = parsed_date.format(&#34;%Y %B %d&#34;).to_string();

    Ok(date)
  }</code></pre>
<p>Returning a trait object <code>Box&lt;dyn std::error::Error&gt;</code> is very convenient when we want to return multiple errors!</p>
<p>See also: <a href="https://github.com/dtolnay/anyhow" target="_blank" rel="noopener"><code>anyhow</code></a>, <a href="https://github.com/yaahc/eyre" target="_blank" rel="noopener"><code>eyre</code></a></p>
<h2 id="Match-boxed-errors"><a href="#Match-boxed-errors" title="Match boxed errors"></a>Match boxed errors</h2><p>So far, we’ve only printed the errors in the <code>main</code> function but not handled them. If we want to handle and recover from boxed errors, we need to “downcast” them:</p>
<pre><code>  use chrono::NaiveDate;
  use std::collections::HashMap;

  fn main() {
    match get_current_date() {
      Ok(date) =&gt; println!(&#34;We&#39;ve time travelled to {}!!&#34;, date),
<span>-     Err(e) =&gt; eprintln!(&#34;Oh noes, we don&#39;t know which era we&#39;re in! :( \n  {}&#34;, e),</span>
<span>+     Err(e) =&gt; {</span>
<span>+       eprintln!(&#34;Oh noes, we don&#39;t know which era we&#39;re in! :(&#34;);</span>
<span>+       if let Some(err) = e.downcast_ref::&lt;reqwest::Error&gt;() {</span>
<span>+         eprintln!(&#34;Request Error: {}&#34;, err)</span>
<span>+       } else if let Some(err) = e.downcast_ref::&lt;chrono::format::ParseError&gt;() {</span>
<span>+         eprintln!(&#34;Parse Error: {}&#34;, err)</span>
<span>+       }</span>
<span>+     }</span>
    }
  }

  fn get_current_date() -&gt; Result&lt;String, Box&lt;dyn std::error::Error&gt;&gt; {
    let url = &#34;https://postman-echo.com/time/object&#34;;
    let res = reqwest::blocking::get(url)?.json::&lt;HashMap&lt;String, i32&gt;&gt;()?;

    let formatted_date = format!(&#34;{}-{}-{}&#34;, res[&#34;years&#34;], res[&#34;months&#34;] + 1, res[&#34;date&#34;]);
    let parsed_date = NaiveDate::parse_from_str(formatted_date.as_str(), &#34;%Y-%m-%d&#34;)?;
    let date = parsed_date.format(&#34;%Y %B %d&#34;).to_string();

    Ok(date)
  }</code></pre>
<p>Notice how we need to be aware of the implementation details (different errors inside) of <code>get_current_date</code> to be able to downcast them inside <code>main</code>.</p>
<p>See also: <a href="https://doc.rust-lang.org/std/error/trait.Error.html#method.downcast" target="_blank" rel="noopener"><code>downcast</code></a>, <a href="https://doc.rust-lang.org/std/error/trait.Error.html#method.downcast_mut" target="_blank" rel="noopener"><code>downcast_mut</code></a></p>
<h2 id="Applications-vs-Libraries"><a href="#Applications-vs-Libraries" title="Applications vs Libraries"></a>Applications vs Libraries</h2><p>As mentioned previously, the downside to boxed errors is that if we want to handle the underlying errors, we need to be aware of the implementation details. When we return something as <code>Box&lt;dyn std::error::Error&gt;</code>, the concrete type information is erased. To handle the different errors in different ways, we need to downcast them to concrete types and this casting can fail at runtime.</p>
<p>However, saying something is a “downside” is not very useful without context. A good rule of thumb is to question whether the code you’re writing is an “application” or a “library”:</p>
<h3 id="Application"><a href="#Application" title="Application"></a>Application</h3><ul>
<li>The code you’re writing would be used by end users.</li>
<li>Most errors generated by application code won’t be handled but instead logged or reported to the user.</li>
<li>It’s okay to use boxed errors.</li>
</ul>
<h3 id="Library"><a href="#Library" title="Library"></a>Library</h3><ul>
<li>The code you’re writing would be consumed by other code. A “library” can be open source crates, internal libraries etc</li>
<li>Errors are part of your library’s API, so your consumers know what errors to expect and recover from.</li>
<li>Errors from your library are often handled by your consumers so they need to be structured and easy to perform <a href="https://doc.rust-lang.org/1.30.0/book/2018-edition/ch06-02-match.html#matches-are-exhaustive" target="_blank" rel="noopener">exhaustive match</a> on.</li>
<li>If you return boxed errors, then your consumers need to be aware of the errors created by your code, your dependencies, and so on!</li>
<li>Instead of boxed errors, we can return custom errors.</li>
</ul>
<h2 id="Create-custom-errors"><a href="#Create-custom-errors" title="Create custom errors"></a>Create custom errors</h2><p>For library code, we can convert all the errors to our own custom error and propagate them instead of boxed errors. In our example, we currently have two errors - <code>reqwest::Error</code> and <code>chrono::format::ParseError</code>. We can convert them to <code>MyCustomError::HttpError</code> and <code>MyCustomError::ParseError</code> respectively.</p>
<p>Let’s start by creating an enum to hold our two error variants:</p>
<pre><code>

<span>pub</span> <span>enum</span> MyCustomError <span>{</span>
  HttpError<span>,</span>
  ParseError<span>,</span>
<span>}</span></code></pre>
<p>The <a href="https://doc.rust-lang.org/std/error/trait.Error.html" target="_blank" rel="noopener"><code>Error</code></a> trait requires us to implement the <a href="https://doc.rust-lang.org/std/fmt/trait.Debug.html" target="_blank" rel="noopener"><code>Debug</code></a> and <a href="https://doc.rust-lang.org/std/fmt/trait.Display.html" target="_blank" rel="noopener"><code>Display</code></a> traits:</p>
<pre><code>

<span>use</span> std<span>:</span><span>:</span>fmt<span>;</span>

<span>#[derive(Debug)]</span>
<span>pub</span> <span>enum</span> MyCustomError <span>{</span>
  HttpError<span>,</span>
  ParseError<span>,</span>
<span>}</span>

<span>impl</span> std<span>:</span><span>:</span>error<span>:</span><span>:</span>Error <span>for</span> MyCustomError <span>{</span><span>}</span>

<span>impl</span> fmt<span>:</span><span>:</span>Display <span>for</span> MyCustomError <span>{</span>
  <span>fn</span> <span>fmt</span><span>(</span><span>&amp;</span><span>self</span><span>,</span> f<span>:</span> <span>&amp;</span><span>mut</span> fmt<span>:</span><span>:</span>Formatter<span>)</span> <span>-&gt;</span> fmt<span>:</span><span>:</span>Result <span>{</span>
    <span>match</span> <span>self</span> <span>{</span>
      MyCustomError<span>:</span><span>:</span>HttpError <span>=</span><span>&gt;</span> <span>write!</span><span>(</span>f<span>,</span> <span>&#34;HTTP Error&#34;</span><span>)</span><span>,</span>
      MyCustomError<span>:</span><span>:</span>ParseError <span>=</span><span>&gt;</span> <span>write!</span><span>(</span>f<span>,</span> <span>&#34;Parse Error&#34;</span><span>)</span><span>,</span>
    <span>}</span>
  <span>}</span>
<span>}</span></code></pre>
<p>We’ve created our own custom error!</p>
<p>This is obviously a simple example as the error variants don’t contain much information about the error. But this should be sufficient as a starting point for creating more complex and realistic custom errors. Here are some real life examples: <a href="https://github.com/BurntSushi/ripgrep/blob/12.1.1/crates/regex/src/error.rs" target="_blank" rel="noopener">ripgrep</a>, <a href="https://github.com/seanmonstar/reqwest/blob/v0.10.7/src/error.rs" target="_blank" rel="noopener">reqwest</a>, <a href="https://github.com/BurntSushi/rust-csv/blob/master/src/error.rs" target="_blank" rel="noopener">csv</a> and <a href="https://github.com/serde-rs/json/blob/master/src/error.rs" target="_blank" rel="noopener">serde_json</a></p>
<p>See also: <a href="https://github.com/dtolnay/thiserror" target="_blank" rel="noopener"><code>thiserror</code></a>, <a href="https://github.com/shepmaster/snafu" target="_blank" rel="noopener"><code>snafu</code></a></p>
<h2 id="Bubble-up-custom-errors"><a href="#Bubble-up-custom-errors" title="Bubble up custom errors"></a>Bubble up custom errors</h2><p>Let’s update our code to return the custom errors we just created:</p>
<pre><code>  // main.rs

<span>+ mod error;</span>

  use chrono::NaiveDate;
<span>+ use error::MyCustomError;</span>
  use std::collections::HashMap;

  fn main() {
    // skipped, will get back later
  }

<span>- fn get_current_date() -&gt; Result&lt;String, Box&lt;dyn std::error::Error&gt;&gt; {</span>
<span>+ fn get_current_date() -&gt; Result&lt;String, MyCustomError&gt; {</span>
    let url = &#34;https://postman-echo.com/time/object&#34;;
<span>-   let res = reqwest::blocking::get(url)?.json::&lt;HashMap&lt;String, i32&gt;&gt;()?;</span>
<span>+   let res = reqwest::blocking::get(url)</span>
<span>+     .map_err(|_| MyCustomError::HttpError)?</span>
<span>+     .json::&lt;HashMap&lt;String, i32&gt;&gt;()</span>
<span>+     .map_err(|_| MyCustomError::HttpError)?;</span>

    let formatted_date = format!(&#34;{}-{}-{}&#34;, res[&#34;years&#34;], res[&#34;months&#34;] + 1, res[&#34;date&#34;]);
<span>-   let parsed_date = NaiveDate::parse_from_str(formatted_date.as_str(), &#34;%Y-%m-%d&#34;)?;</span>
<span>+   let parsed_date = NaiveDate::parse_from_str(formatted_date.as_str(), &#34;%Y-%m-%d&#34;)</span>
<span>+     .map_err(|_| MyCustomError::ParseError)?;</span>
    let date = parsed_date.format(&#34;%Y %B %d&#34;).to_string();

    Ok(date)
  }</code></pre>
<p>Notice how we’re using <code>map_err</code> to convert the error from one type to another type.</p>
<p>But things got verbose as a result - our function is littered with these <code>map_err</code> calls. We can implement the <a href="https://doc.rust-lang.org/std/convert/trait.From.html" target="_blank" rel="noopener"><code>From</code></a> trait to automatically coerce the error types when we use the <code>?</code> operator:</p>
<pre><code>  // error.rs

  use std::fmt;

  #[derive(Debug)]
  pub enum MyCustomError {
    HttpError,
    ParseError,
  }

  impl std::error::Error for MyCustomError {}

  impl fmt::Display for MyCustomError {
    fn fmt(&amp;self, f: &amp;mut fmt::Formatter) -&gt; fmt::Result {
      match self {
        MyCustomError::HttpError =&gt; write!(f, &#34;HTTP Error&#34;),
        MyCustomError::ParseError =&gt; write!(f, &#34;Parse Error&#34;),
      }
    }
  }

<span>+ impl From&lt;reqwest::Error&gt; for MyCustomError {</span>
<span>+   fn from(_: reqwest::Error) -&gt; Self {</span>
<span>+     MyCustomError::HttpError</span>
<span>+   }</span>
<span>+ }</span>

<span>+ impl From&lt;chrono::format::ParseError&gt; for MyCustomError {</span>
<span>+   fn from(_: chrono::format::ParseError) -&gt; Self {</span>
<span>+     MyCustomError::ParseError</span>
<span>+   }</span>
<span>+ }</span></code></pre>
<pre><code>  // main.rs

  mod error;

  use chrono::NaiveDate;
  use error::MyCustomError;
  use std::collections::HashMap;

  fn main() {
    // skipped, will get back later
  }

  fn get_current_date() -&gt; Result&lt;String, MyCustomError&gt; {
    let url = &#34;https://postman-echo.com/time/object&#34;;
<span>-   let res = reqwest::blocking::get(url)</span>
<span>-     .map_err(|_| MyCustomError::HttpError)?</span>
<span>-     .json::&lt;HashMap&lt;String, i32&gt;&gt;()</span>
<span>-     .map_err(|_| MyCustomError::HttpError)?;</span>
<span>+   let res = reqwest::blocking::get(url)?.json::&lt;HashMap&lt;String, i32&gt;&gt;()?;</span>

    let formatted_date = format!(&#34;{}-{}-{}&#34;, res[&#34;years&#34;], res[&#34;months&#34;] + 1, res[&#34;date&#34;]);
<span>-   let parsed_date = NaiveDate::parse_from_str(formatted_date.as_str(), &#34;%Y-%m-%d&#34;)</span>
<span>-     .map_err(|_| MyCustomError::ParseError)?;</span>
<span>+   let parsed_date = NaiveDate::parse_from_str(formatted_date.as_str(), &#34;%Y-%m-%d&#34;)?;</span>
    let date = parsed_date.format(&#34;%Y %B %d&#34;).to_string();

    Ok(date)
  }</code></pre>
<p>We’ve removed <code>map_err</code> and the code looks much cleaner!</p>
<p>However, <code>From</code> trait is not magic and there are times when we need to use <code>map_err</code>. In the above example, we’ve moved the type conversion from inside the <code>get_current_date</code> function to the <code>From&lt;X&gt; for MyCustomError</code> implementation. This works well when the information needed to convert from one error to <code>MyCustomError</code> can be obtained from the original error object. If not, we need to use <code>map_err</code> inside <code>get_current_date</code>.</p>
<h2 id="Match-custom-errors"><a href="#Match-custom-errors" title="Match custom errors"></a>Match custom errors</h2><p>We’ve ignored the changes in <code>main</code> until now, here’s how we can handle the custom errors:</p>
<pre><code>  // main.rs

  mod error;

  use chrono::NaiveDate;
  use error::MyCustomError;
  use std::collections::HashMap;

  fn main() {
    match get_current_date() {
      Ok(date) =&gt; println!(&#34;We&#39;ve time travelled to {}!!&#34;, date),
      Err(e) =&gt; {
        eprintln!(&#34;Oh noes, we don&#39;t know which era we&#39;re in! :(&#34;);
<span>-       if let Some(err) = e.downcast_ref::&lt;reqwest::Error&gt;() {</span>
<span>-         eprintln!(&#34;Request Error: {}&#34;, err)</span>
<span>-       } else if let Some(err) = e.downcast_ref::&lt;chrono::format::ParseError&gt;() {</span>
<span>-         eprintln!(&#34;Parse Error: {}&#34;, err)</span>
<span>-       }</span>
<span>+       match e {</span>
<span>+         MyCustomError::HttpError =&gt; eprintln!(&#34;Request Error: {}&#34;, e),</span>
<span>+         MyCustomError::ParseError =&gt; eprintln!(&#34;Parse Error: {}&#34;, e),</span>
<span>+       }</span>
      }
    }
  }

  fn get_current_date() -&gt; Result&lt;String, MyCustomError&gt; {
    let url = &#34;https://postman-echo.com/time/object&#34;;
    let res = reqwest::blocking::get(url)?.json::&lt;HashMap&lt;String, i32&gt;&gt;()?;

    let formatted_date = format!(&#34;{}-{}-{}&#34;, res[&#34;years&#34;], res[&#34;months&#34;] + 1, res[&#34;date&#34;]);
    let parsed_date = NaiveDate::parse_from_str(formatted_date.as_str(), &#34;%Y-%m-%d&#34;)?;
    let date = parsed_date.format(&#34;%Y %B %d&#34;).to_string();

    Ok(date)
  }</code></pre>
<p>Notice how unlike boxed errors, we can actually match on the variants inside <code>MyCustomError</code> enum.</p>
<h2 id="Conclusion"><a href="#Conclusion" title="Conclusion"></a>Conclusion</h2><p>Thanks for reading! I hope this post was helpful in introducing the basics of error handling in Rust. I’ve added the examples to a <a href="https://github.com/sheshbabu/rust-error-handling-examples" target="_blank" rel="noopener">repo in GitHub</a> which you can use for practice. If you’ve more questions, please contact me at sheshbabu [at] gmail.com. Feel free to follow me in <a href="https://twitter.com/sheshbabu" target="_blank" rel="noopener">Twitter</a> for more posts like this :)</p>
</div></div>
  </body>
</html>
